@ECHO OFF
SETLOCAL
:START

SET SCRIPTPATH=%~dp0
SET SCRIPTDRIVE=%SCRIPTPATH:~0,2%


::Set some common paths
SET REPOSITORY=%EMMSERVERBASE%
IF NOT EXIST "%REPOSITORY%" GOTO HELP

SET ROOT=%SCRIPTPATH%
SET MCSROOT=%ROOT%\Build

SET MCROOT=%MCSROOT%\Minecraft
SET SMROOT=%MCSROOT%\
SET CACHEROOT=%MCSROOT%\Cache
SET AVROOT=%MCSROOT%\AlphaVespucci
SET OVERVIEWERROOT=%MCSROOT%\Overviewer
SET BACKUPROOT=%MCSROOT%\Backups
SET MAPROOT=%MCSROOT%\Maps


:: Change to the script's path
%SCRIPTDRIVE%
CD %SCRIPTPATH%


:: Create the folder hieararchy
IF NOT EXIST "%MCSROOT%" MKDIR "%MCSROOT%"
IF NOT EXIST "%MCROOT%" MKDIR "%MCROOT%"
IF NOT EXIST "%SMROOT%" MKDIR "%SMROOT%"
IF NOT EXIST "%CACHEROOT%" MKDIR "%CACHEROOT%"
IF NOT EXIST "%AVROOT%" MKDIR "%AVROOT%"
IF NOT EXIST "%OVERVIEWERROOT%" MKDIR "%OVERVIEWERROOT%"
IF NOT EXIST "%BACKUPROOT%" MKDIR "%BACKUPROOT%"
IF NOT EXIST "%MAPROOT%" MKDIR "%MAPROOT%"


::Copy the files we need to the package
XCOPY /Y "%REPOSITORY%\Minecraft\minecraft_server.jar" "%MCROOT%"
IF EXIST "%REPOSITORY%\AlphaVespucci" XCOPY /Y "%REPOSITORY%\AlphaVespucci\*" "%AVROOT%"
IF EXIST "%REPOSITORY%\Overviewer" XCOPY /Y /S "%REPOSITORY%\Overviewer\*" "%OVERVIEWERROOT%"

CD %MCROOT:~0,2%
CD "%MCROOT%"
ECHO stop | java -jar "%MCROOT%\minecraft_server.jar" nogui
GOTO END

:HELP
ECHO The environment variable EMMSERVERBASE should point to a repository where EMM test sources can be found
GOTO END

:END
ENDLOCAL